apiVersion: v1
kind: Pod
metadata:
  name: sa-test
  namespace: dev
spec:
  serviceAccountName: my-sa
  containers:
    - name: app
      image: bitnami/kubectl:latest
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]